# Generated by Django 3.0 on 2020-01-08 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_auto_20200103_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
