# Generated by Django 3.0 on 2020-06-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_photography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photography',
            old_name='post_img',
            new_name='photo',
        ),
    ]
